# Generated by Django 3.1.3 on 2021-01-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monstertracker', '0003_auto_20210105_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drop',
            old_name='rarityAvg',
            new_name='rarity',
        ),
        migrations.AlterField(
            model_name='drop',
            name='sellAvg',
            field=models.IntegerField(null=True),
        ),
    ]
