# Generated by Django 3.1.3 on 2021-01-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monstertracker', '0004_auto_20210107_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonsterList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortedMonsterList', models.ManyToManyField(related_name='sortedMonsterList', to='monstertracker.Monster')),
            ],
        ),
    ]
