# Generated by Django 3.1.3 on 2021-01-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monstertracker', '0005_monsterlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monster',
            old_name='profitPerKill',
            new_name='grossIncomePerKill',
        ),
        migrations.AddField(
            model_name='drop',
            name='rolls',
            field=models.IntegerField(null=True),
        ),
    ]
