# Generated by Django 3.1.3 on 2021-01-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monstertracker', '0006_auto_20210109_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='grossIncomePerKill',
            field=models.FloatField(null=True),
        ),
    ]
