# Generated by Django 3.1.3 on 2021-01-10 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monstertracker', '0008_auto_20210110_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='dropList',
        ),
        migrations.AddField(
            model_name='drop',
            name='monster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monstertracker.monster'),
        ),
    ]
