# Generated by Django 3.1.3 on 2021-01-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monstertracker', '0009_auto_20210110_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drop',
            name='monster',
        ),
        migrations.AddField(
            model_name='monster',
            name='dropList',
            field=models.ManyToManyField(to='monstertracker.Drop'),
        ),
    ]
